server:
  port: 1234
spring:
  application:
    name: yuni-core
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/yuni_cms?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  profiles:
    include: common
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag  # 全局逻辑删除标识
      logic-delete-value: 1        # 删除值
      logic-not-delete-value: 0    # 非删除值
      id-type: auto
logging:
  level:
    com:
      yuier:
        mapper: debug
user-agent: user-agent
smms:
  baseurl: https://smms.app/api/v2
  upload-image: /upload
  api-token: api-token
  authorization: authorization
  cookie: cookie
COS:
  secret-id: secret-id
  secret-key: secret-key
  bucket-name:
    one-bucket: one-bucket-name

api:
  bilibili:
    base: http://api.bilibili.com/

headers:
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67
  referer:
    bilibili: https://www.bilibili.com/
  cookies:
    bilibili: cookies-to-bilibili