base-urls:
  one-bot: http://url/to/one-bot/
  core: http://url/to/core/
  function: http://url/to/function/
  dd: http://url/to/dd/

bot:
  owner: qq_of_owner

spring:
  config:
    activate:
      on-profile: common